owncloud-ci/php

Dockerfile
Related to the discussion here:
https://github.com/owncloud/qa-enterprise/pull/115#issuecomment-357640174
cc @individual-it  
If approved - needs backport to other version
=> Add required packages for running ui tests in php image

Dockerfile, rootfs/etc/apache2/conf-enabled/security.conf, rootfs/etc/apache2/conf-enabled/servername.conf, rootfs/etc/apache2/sites-enabled/000-default.conf, rootfs/etc/apache2/templates/base.conf, rootfs/usr/local/bin/apachectl
Superseeds #12 (could not push to remote branch from @individual-it :'( )
Contains a wrapper called `apachectl-ci` which accepts environment vars for setting the document root: `APACHE_WEBROOT` 
It also already includes `APACHE_TEMPLATE_PATH` and `APACHE_CONFIG_TEMPLATE` to override the very basic template file.
Use cases:
- using apache as simple webdav endpoint server for `files_external` tests
- having more specific apache configs for certain applications 
Needs backporting to (be careful with package names since some other php versions use ppa repositories)
=> Add apache for ci tasks

Dockerfile
This enables apache modules by default.
It will also include the webdav modules to use the container for testing files_external_webdav
If approved - I will backport this change to the open PRs
=> enable apache modules by default

Dockerfile
=> [master] use node 8

rootfs/etc/php/7.0/apache2/conf.d/10-opcache-custom.ini, rootfs/etc/php/7.0/cli/conf.d/10-opcache-custom.ini, rootfs/etc/php/7.0/fpm/conf.d/10-opcache-custom.ini, rootfs/etc/php/7.0/mods-available/opcache-custom.ini, rootfs/etc/php/7.0/phpdbg/conf.d/10-opcache-custom.ini
Some acceptance tests call the api to change a system setting - `config.php` is however cached by php and thus tests fail or are flaky
=> [master] revalidate file changes on every php request

Dockerfile
Phan (static code analysis tool) recommends the usage of `php-ast` for code inspect (ref: https://github.com/phan/phan#getting-started ) 
This PR adds the extension
Note: no backport for php5.6 necessary / available, as php-ast is only provided for php7+ - and phan requires running on php7.0 (but it can check that the code is fully backward compatible with php5.6 )
=> add php-ast extension

Dockerfile
In the past we removed `php-memcached` as we were running into segfaults #33 
With this PR I want to reintroduce memcached to be used during static code analysis (phan)
=> [7.2] add php-memcached again

rootfs/etc/apache2/templates/ssl, rootfs/usr/local/bin/apachectl
messed up #73 starting fresh
this PR makes it possible to start the apache server with HTTPS by using:
`APACHE_CONFIG_TEMPLATE=ssl`
also `APACHE_SSL_CERT` and `APACHE_SSL_KEY` can be used to configure the SSL certificate and key that should be used.
if the key and certificate file do not exist, they will be created
see: owncloud/core#32550
@patrickjahns  please review
=> allow to start apache with HTTPS

v5.6/Dockerfile.amd64, v5.6/Dockerfile.arm32v7, v5.6/Dockerfile.arm64v8, v7.0/Dockerfile.amd64, v7.0/Dockerfile.arm32v7, v7.0/Dockerfile.arm64v8, v7.1/Dockerfile.amd64, v7.1/Dockerfile.arm32v7, v7.1/Dockerfile.arm64v8, v7.2/Dockerfile.amd64, v7.2/Dockerfile.arm32v7, v7.2/Dockerfile.arm64v8, v7.3/Dockerfile.amd64, v7.3/Dockerfile.arm32v7, v7.3/Dockerfile.arm64v8
the current version of the container does not have rsync installed. The reason might have been the change from ubuntu 16:04 to 18:04 in #101 see https://github.com/owncloud-ci/php/pull/101/files#diff-ebacd6eb223909eb1bf32a1089f94ea4R1
rsync is needed to install the test-runner in acceptance tests, see https://github.com/owncloud/user_ldap/blob/master/.drone.starlark#L1590
=> install rsync in container

v5.6/Dockerfile.arm32v7, v5.6/Dockerfile.arm64v8, v7.0/Dockerfile.arm32v7, v7.0/Dockerfile.arm64v8, v7.1/Dockerfile.arm32v7, v7.1/Dockerfile.arm64v8, v7.2/Dockerfile.arm32v7, v7.2/Dockerfile.arm64v8, v7.3/Dockerfile.arm32v7, v7.3/Dockerfile.arm64v8
These "copy overlay" in the various `Dockerfile` looked inconsistent.
They should mention the `overlay-*` for their architecture?
=> consistent Dockerfile copy overlay

.drone.star
I  tried restarting the last merge CI in order to update the docker images so that they have the latest patch releases of PHP 7.3 and 7.4, and the official release of PHP 8.0. But CI gives errors in the prepublish step:
https://cloud.drone.io/owncloud-ci/php/48/1/2
```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
So let's try this little PR and see what happens.
=> Remove whitespace from .drone.star

v8.0/Dockerfile.amd64, v8.0/Dockerfile.arm64v8
Nothing "real" is using PHP 8.0 yet, so doing this will not break any configured CI. If we use Ubuntu 20.04 then we will get later versions of other non-PHP stuff that is also built-in to this docker image, `nodejs` for example. That will give us the option to use this `owncloudci/php:8.0` image for various up-to-date stuff when we want.
The immediate thing that I wanted to try is that this should give a newer `nodejs` version as a side-effect.
=> Use Ubuntu 20.04 for PHP 8.0

v8.0/Dockerfile.amd64, v8.0/Dockerfile.arm64v8
In https://drone.owncloud.com/owncloud/activity/1682/2/4 I got:
```
+ make test-js
Makefile:13: *** npm is not available on your system, please install npm.  Stop.
```
That's a bit sad :( - I guess that somehow `npm` came "for free" with `nodejs` version 8 when installing on Ubuntu 18.04, and that it has to be specifically mentioned when installing major version 10 on Ubuntu 20.04.
=> Specifically install npm in Ubuntu 20.04 PHP 8.0 image

v7.4/Dockerfile.amd64, v7.4/Dockerfile.arm64v8
Ubuntu 20.04 has been out and stable for a while now. It comes with PHP 7.4 as the default. It comes with later versions of other things also. In particular we want to have a later `nodejs` and `npm`, which come by default with Ubuntu 20.04.
Existing CI that uses PHP 7.4 includes:
- Behat acceptance tests
- some PHP unit test pipelines
These work fine with Ubuntu 20.04
=> Use Ubuntu 20.04 as the base for PHP 7.4

v7.4/Dockerfile.amd64, v7.4/Dockerfile.arm64v8
This reverts commit 632543508a3d59cf652adbc6f18d27ee77af598a.
There are unit tests failing in core with the Ubuntu 20.04 PHP 7.4 docker image. I need to investigate why, but for now we had better revert back and get CI  green again. Issue https://github.com/owncloud/core/issues/38348
=> Revert "Use Ubuntu 20.04 as the base for PHP 7.4"

v5.6/Dockerfile.amd64, v5.6/Dockerfile.arm64v8, v7.0/Dockerfile.amd64, v7.0/Dockerfile.arm64v8, v7.1/Dockerfile.amd64, v7.1/Dockerfile.arm64v8, v7.2/Dockerfile.amd64, v7.2/Dockerfile.arm64v8, v7.3/Dockerfile.amd64, v7.3/Dockerfile.arm64v8, v7.4-ubuntu20.04/Dockerfile.amd64, v7.4-ubuntu20.04/Dockerfile.arm64v8, v7.4/Dockerfile.amd64, v7.4/Dockerfile.arm64v8, v8.0/Dockerfile.amd64, v8.0/Dockerfile.arm64v8
After re-running the last Merge CI to recreate `owncloudci/php` docker images to get the latest PHP patch releases, we are getting errors in CI like: https://drone.owncloud.com/owncloud/core/29750/5/7
```
ERROR: The php-ast extension must be loaded in order for Phan to work. Either install and enable php-ast, or invoke Phan with the CLI option --allow-polyfill-parser (which is noticeably slower)
```
I get the same when doing `make test-php-phan` locally with PHP 7.4.18
I have to `sudo apt install php7.4-ast` t get rid of that error.
Then I have to also install other extensions using the explicit version number to get `phan` to pass:
```
sudo apt install php7.4-memcached
sudo apt install php7.4-redis
sudo apt install php7.4-imagick
```
It seems that nowadays we have to explicitly mention …
=> Install explicit versions of PHP extensions

v7.0/Dockerfile.amd64, v7.0/Dockerfile.arm64v8, v7.1/Dockerfile.amd64, v7.1/Dockerfile.arm64v8, v7.2/Dockerfile.amd64, v7.2/Dockerfile.arm64v8, v7.3/Dockerfile.amd64, v7.3/Dockerfile.arm64v8, v7.4-ubuntu20.04/Dockerfile.amd64, v7.4-ubuntu20.04/Dockerfile.arm64v8, v7.4/Dockerfile.amd64, v7.4/Dockerfile.arm64v8
https://drone.owncloud.com/owncloud/core/29752/6/7
`lib/private/Memcache/APCu.php:62 PhanUndeclaredClassMethod Call to method __construct from undeclared class \APCIterator (Did you mean to configure a stub with https://github.com/phan/phan/wiki/How-To-Use-Stubs#internal-stubs or to enable the extension providing the class. or class \APCUIterator)`
https://stackoverflow.com/questions/37394828/apciterator-class-not-found-for-php7
ownCloud still has some reference to `APCIterator` (the "modern" version is `APCUIterator`) - that old class is in the backward-compatibility extension for apcu.
I have no idea why this is now needed. I guess that until recently the backward-compatibility extension somehow got automagically selected for install, or?
=> Add apcu-bc backward-compatibility extension to PHP 7.*

latest/Dockerfile.amd64, latest/Dockerfile.arm64v8, v7.3/Dockerfile.amd64, v7.3/Dockerfile.arm64v8, v7.4-ubuntu20.04/Dockerfile.amd64, v7.4-ubuntu20.04/Dockerfile.arm64v8, v7.4/Dockerfile.amd64, v7.4/Dockerfile.arm64v8, v8.0/Dockerfile.amd64, v8.0/Dockerfile.arm64v8
Issue #137 
We have adjusted CI of C10 core, oC10 apps, oCIS and web so that it uses `owncloudci/nodejs:14` for all things that need nodejs (and npm and yarn are the same "bundle" of JS things).
This PR  removes `node` `npm` and `yarn` from the "current" PHP docker images - PHP 7.3, 7.4, 8.0 and "latest". Those are the images that actually get used these days. (We dropped PHP 7.2 in oC10 core and apps 2 weeks ago)
I didn't touch the older PHP images 5.6 7.0 7.1 7.2 - IMO they can stay like they are for "a long time" (= until we decide to delete them, if we ever do that)
After merging this, we will soon find out what other repos use these docker images and also depend on have these JS tools embedded in a PHP docker image.
Comments welcome...
=> Remove node npm yarn from current PHP images

latest/Dockerfile.amd64, latest/Dockerfile.arm64v8, v7.3/Dockerfile.amd64, v7.3/Dockerfile.arm64v8, v7.4-ubuntu20.04/Dockerfile.amd64, v7.4-ubuntu20.04/Dockerfile.arm64v8, v7.4/Dockerfile.amd64, v7.4/Dockerfile.arm64v8, v8.0/Dockerfile.amd64, v8.0/Dockerfile.arm64v8
PR #138 removed node, npm and yarn. Somehow we lost python v2 by doing that - I guess that it happened to be a dependency of one or more of those removed tools.
But we need python v2 for the caldav/carddav test suites. There is not yet a version of those test suites that passes with python v3.
See https://github.com/apple/ccs-caldavtester/issues/39 and https://github.com/apple/ccs-caldavtester/pull/40 for recent progress on that in the upstream repo.
This PR explicitly installs python v2 in the PHP images, so that we can get oC10 core CI green again.
=> Install python v2 in PHP images

v5.6/Dockerfile.amd64, v8.0/Dockerfile.amd64
Switch to the needed PHP version for CI of PHP 5.6 and 8.0
For the PHP 5.6 pipeline, plugins/docker has PHP 7.0 running.
Switch to PHP 5.6 so that later Oracle oci8 etc steps pass.
For the PHP 8.0 pipeline, plugins/docker has PHP 8.1 running.
Switch to PHP 8.0 so that later Oracle oci8 etc steps pass.
Fixes #143
=> Use the needed PHP version for PHP 5.6 and 8.0 pipelines

v7.0/Dockerfile.amd64, v7.1/Dockerfile.amd64, v7.2/Dockerfile.amd64, v8.0/Dockerfile.amd64
to the current versions listed at https://pecl.php.net/package/oci8
=> Bump oci8 versions

.drone.star, v8.1/Dockerfile.amd64, v8.1/Dockerfile.arm64v8, v8.1/manifest.tmpl, v8.1/overlay-amd64/etc/php/8.1/apache2/conf.d/20-oci8.ini, v8.1/overlay-amd64/etc/php/8.1/cli/conf.d/20-oci8.ini, v8.1/overlay-amd64/etc/php/8.1/fpm/conf.d/20-oci8.ini, v8.1/overlay-amd64/etc/php/8.1/mods-available/oci8.ini, v8.1/overlay-amd64/etc/php/8.1/phpdbg/conf.d/20-oci8.ini, v8.1/overlay/etc/ImageMagick-6/policy.xml, v8.1/overlay/etc/apache2/conf-enabled/security.conf, v8.1/overlay/etc/apache2/conf-enabled/servername.conf, v8.1/overlay/etc/apache2/sites-enabled/000-default.conf, v8.1/overlay/etc/apache2/templates/base, v8.1/overlay/etc/apache2/templates/ssl, v8.1/overlay/etc/apache2/templates/webdav, v8.1/overlay/etc/ldap/ldap.conf, v8.1/overlay/etc/php/8.1/apache2/conf.d/10-opcache-custom.ini, v8.1/overlay/etc/php/8.1/cli/conf.d/10-opcache-custom.ini, v8.1/overlay/etc/php/8.1/fpm/conf.d/10-opcache-custom.ini, v8.1/overlay/etc/php/8.1/mods-available/opcache-custom.ini, v8.1/overlay/etc/php/8.1/phpdbg/conf.d/10-opcache-custom.ini, v8.1/overlay/root/.bowerrc, v8.1/overlay/usr/local/bin/apachectl
It will be useful to have PHP 8.1 also available for when people start trying run things with PHP 8.*
- based on owncloud/ubuntu:20.04 (the same as the PHP 8.0 image).
- oci8 versions listed at https://pecl.php.net/package/oci8 - I pinned the oci8 installer to 3.2.1 (the current latest) for PHP 8.1.
IMO we can sort out images for PHP 7.4, 8.0, 8.1 with Ubuntu 22.04 after this - see PR https://github.com/owncloud-docker/ubuntu/pull/102 which, hopefully, will get an "ownCloud" Ubuntu 22.04 docker image published.
=> Create PHP 8.1

latest/Dockerfile.amd64, latest/Dockerfile.arm64v8, v5.6/Dockerfile.amd64, v5.6/Dockerfile.arm64v8, v7.0/Dockerfile.amd64, v7.0/Dockerfile.arm64v8, v7.1/Dockerfile.amd64, v7.1/Dockerfile.arm64v8, v7.2/Dockerfile.amd64, v7.2/Dockerfile.arm64v8, v7.3/Dockerfile.amd64, v7.3/Dockerfile.arm64v8, v7.4-ubuntu20.04/Dockerfile.amd64, v7.4-ubuntu20.04/Dockerfile.arm64v8, v7.4-ubuntu22.04/Dockerfile.amd64, v7.4-ubuntu22.04/Dockerfile.arm64v8, v7.4/Dockerfile.amd64, v7.4/Dockerfile.arm64v8, v8.0/Dockerfile.amd64, v8.0/Dockerfile.arm64v8, v8.1/Dockerfile.amd64, v8.1/Dockerfile.arm64v8
Issue https://github.com/owncloud-ci/retry/issues/7
I added `retry` to all the image tags because we have CI that does upgrade-testing, and that has pipelines that start by installing old oC10 releases on an old PHP version. So those images are still used a little bit. Having `retry` in all the tagged versions will avoid "random problems" when it gets used in CI.
=> Add the retry script to owncloudci/php images

.drone.star, v8.2/Dockerfile.amd64, v8.2/Dockerfile.arm64v8, v8.2/manifest.tmpl, v8.2/overlay-amd64/etc/php/8.2/apache2/conf.d/20-oci8.ini, v8.2/overlay-amd64/etc/php/8.2/cli/conf.d/20-oci8.ini, v8.2/overlay-amd64/etc/php/8.2/fpm/conf.d/20-oci8.ini, v8.2/overlay-amd64/etc/php/8.2/mods-available/oci8.ini, v8.2/overlay-amd64/etc/php/8.2/phpdbg/conf.d/20-oci8.ini, v8.2/overlay/etc/ImageMagick-6/policy.xml, v8.2/overlay/etc/apache2/conf-enabled/security.conf, v8.2/overlay/etc/apache2/conf-enabled/servername.conf, v8.2/overlay/etc/apache2/sites-enabled/000-default.conf, v8.2/overlay/etc/apache2/templates/base, v8.2/overlay/etc/apache2/templates/ssl, v8.2/overlay/etc/apache2/templates/webdav, v8.2/overlay/etc/ldap/ldap.conf, v8.2/overlay/etc/php/8.2/apache2/conf.d/10-opcache-custom.ini, v8.2/overlay/etc/php/8.2/cli/conf.d/10-opcache-custom.ini, v8.2/overlay/etc/php/8.2/fpm/conf.d/10-opcache-custom.ini, v8.2/overlay/etc/php/8.2/mods-available/opcache-custom.ini, v8.2/overlay/etc/php/8.2/phpdbg/conf.d/10-opcache-custom.ini, v8.2/overlay/root/.bowerrc, v8.2/overlay/usr/local/bin/apachectl
required for https://github.com/owncloud/core/pull/40981
=> feat: add php8.2 image

v7.4/Dockerfile.multiarch
Ubuntu 20.04 is very old anyway, so use Ubuntu 22.04 as the base image for the "default" PHP 7.4 docker image.
=> chore: bump Ubuntu from 20.04 to 22.04 for the default PHP 7.4 image

v7.4-ubuntu22.04/Dockerfile.multiarch, v7.4/Dockerfile.multiarch
https://github.com/owncloud/files_classifier/pull/796 added `exif` tool to allow looking into PDF files for classification.
That needs `libimage-exiftool-perl`.
With the new Freexian PHP 7.4 `owncloudci/php` image, we can't do general `apt install` to it on-the-fly in CI, because that causes it to try to access our Freexian deb mirror, and that requires authentication.
So for CI, it will be easiest to have software like this pre-installed. And this PHP image is only for use in CI, so it's not an issue for production installs that use docker - they are based on `owncloud-docker/php`
=> chore: install libimage-exiftool-perl for files_classifier

.drone.star, v7.4-ubuntu22.04/Dockerfile.multiarch, v7.4/Dockerfile.multiarch
Use the "secrets" functionality of docker buildkit to pass in the authentication for the Freexian deb package server.
The drone secrets are put into temporary files that are passed into `owncloudci/drone-docker-buildx` and are used there to access the Freexian deb package server. Those files are discarded at the end of the CI pipeline, they do not end up in the published image details.
=> chore: use docker buildkit secret

v8.0/Dockerfile.multiarch, v8.1/Dockerfile.multiarch, v8.2/Dockerfile.multiarch, v8.3/Dockerfile.multiarch
These were only being used to test things with PHP8.x.
We might as well move them forward to be based on Ubuntu 22.04.
=> chore: bump the PHP8 images to use Ubuntu 22.04
