- Dockerfile
> [5.6] added libxml2-utils for running uitests 

- Dockerfile
> [7.0] added libxml2-utils for running uitests 

- Dockerfile
> [7.1] added libxml2-utils for running uitests 

- Dockerfile
> [7.2] added libxml2-utils for running uitests 

- Dockerfile
Backports will follow as soon as merged
> add yarn to php image

- Dockerfile
need to be able to use this image to run tests on the `user_ldap` app
> install php-ldap

- Dockerfile
> [5.6] install php-ldap

- Dockerfile
> [7.0] install php-ldap

- Dockerfile
> [7.1] install php-ldap

- Dockerfile
> [7.2] install php-ldap

- Dockerfile
With php7.2 and memcached we are running into segfaults - remove it for now:
https://github.com/owncloud/core/pull/29635#issuecomment-359593147
https://github.com/owncloud/core/pull/30020#issuecomment-363426449
> [7.2] remove memcached

- Dockerfile
> [7.0] use node 8

- Dockerfile
> [5.6] use node 8

- Dockerfile
> [7.1] use node 8

- Dockerfile
> [7.2] use node 8

- rootfs/etc/php/5.6/apache2/conf.d/10-opcache-custom.ini
- rootfs/etc/php/5.6/cli/conf.d/10-opcache-custom.ini
- rootfs/etc/php/5.6/fpm/conf.d/10-opcache-custom.ini
- rootfs/etc/php/5.6/mods-available/opcache-custom.ini
- rootfs/etc/php/5.6/phpdbg/conf.d/10-opcache-custom.ini
> [5.6] revalidate file changes on every php request

- rootfs/etc/php/7.0/apache2/conf.d/10-opcache-custom.ini
- rootfs/etc/php/7.0/cli/conf.d/10-opcache-custom.ini
- rootfs/etc/php/7.0/fpm/conf.d/10-opcache-custom.ini
- rootfs/etc/php/7.0/mods-available/opcache-custom.ini
- rootfs/etc/php/7.0/phpdbg/conf.d/10-opcache-custom.ini
> [7.0] revalidate file changes on every php request

- rootfs/etc/php/7.1/apache2/conf.d/10-opcache-custom.ini
- rootfs/etc/php/7.1/cli/conf.d/10-opcache-custom.ini
- rootfs/etc/php/7.1/fpm/conf.d/10-opcache-custom.ini
- rootfs/etc/php/7.1/mods-available/opcache-custom.ini
- rootfs/etc/php/7.1/phpdbg/conf.d/10-opcache-custom.ini
> [7.1] revalidate file changes on every php request

- rootfs/etc/php/7.2/apache2/conf.d/10-opcache-custom.ini
- rootfs/etc/php/7.2/cli/conf.d/10-opcache-custom.ini
- rootfs/etc/php/7.2/fpm/conf.d/10-opcache-custom.ini
- rootfs/etc/php/7.2/mods-available/opcache-custom.ini
- rootfs/etc/php/7.2/phpdbg/conf.d/10-opcache-custom.ini
> [7.2] revalidate file changes on every php request

- rootfs/root/.bowerrc
> [7.0] allow running bower as root user

- rootfs/root/.bowerrc
Old issue appeared again when wanting to use the php images for building (ref: https://github.com/owncloud-ci/core/pull/5 )
> allow running bower as root user

- rootfs/root/.bowerrc
> [7.1] allow running bower as root user

- rootfs/root/.bowerrc
> [7.2] allow running bower as root user

- rootfs/root/.bowerrc
> [5.6] allow running bower as root user

- Dockerfile
> [7.2] add php-ast extension

- Dockerfile
> [7.0] add php-ast extension

- Dockerfile
> [7.1] add php-ast extension

- rootfs/etc/apache2/templates/ssl
- rootfs/usr/local/bin/apachectl
> [7.1] allow to start apache with HTTPS

- rootfs/etc/apache2/templates/ssl
- rootfs/usr/local/bin/apachectl
> [7.2] allow to start apache with HTTPS

- rootfs/etc/apache2/templates/ssl
- rootfs/usr/local/bin/apachectl
> [7.0] allow to start apache with HTTPS

- rootfs/etc/apache2/templates/ssl
- rootfs/usr/local/bin/apachectl
> [5.6] allow to start apache with HTTPS

- Dockerfile
> add missing extension: ast, apcu, smbclient, imagick, redis

- Dockerfile
> [7.3] adding php-memcached

- rootfs/etc/ldap/ldap.conf
needed to run ldap over TLS see https://github.com/owncloud/user_ldap/issues/348
> accept self-signed certificates as ldap client

- rootfs/etc/ldap/ldap.conf
> [5.6] accept self-signed certificates as ldap client

- rootfs/etc/ldap/ldap.conf
> [7.0] accept self-signed certificates as ldap client

- rootfs/etc/ldap/ldap.conf
> [7.1] accept self-signed certificates as ldap client

- rootfs/etc/ldap/ldap.conf
> [7.3] accept self-signed certificates as ldap client

- .drone.star
> Remove drone volumes

- latest/Dockerfile.amd64
- v8.0/Dockerfile.amd64
Fix https://github.com/owncloud-ci/php/issues/118
> Pin oci8 version

- v7.4/Dockerfile.amd64
- v7.4/overlay-amd64/etc/php/7.4/apache2/conf.d/20-krb5.ini
- v7.4/overlay-amd64/etc/php/7.4/cli/conf.d/20-krb5.ini
- v7.4/overlay-amd64/etc/php/7.4/fpm/conf.d/20-krb5.ini
- v7.4/overlay-amd64/etc/php/7.4/mods-available/krb5.ini
- v7.4/overlay-amd64/etc/php/7.4/phpdbg/conf.d/20-krb5.ini
For the time being only 7.4 is required ... will add it to other images in follow up PRs
> feat: add php extension krb5

- .drone.star
This way it can be asserted that expected php extensions are properly built i the images.
Will use this in follow up PRs of #157
> test: assert that images hold required php extensions

- v7.4-ubuntu20.04/Dockerfile.multiarch
- v7.4-ubuntu22.04/Dockerfile.multiarch
- v7.4/Dockerfile.multiarch
- v8.0/Dockerfile.multiarch
- v8.1/Dockerfile.multiarch
- v8.2/Dockerfile.multiarch
- v8.3/Dockerfile.multiarch
> chore: only install Oracle on amd64

- v7.4-ubuntu20.04/Dockerfile.multiarch
- v7.4-ubuntu22.04/Dockerfile.multiarch
- v7.4/Dockerfile.multiarch
- v8.0/Dockerfile.multiarch
- v8.1/Dockerfile.multiarch
- v8.2/Dockerfile.multiarch
- v8.3/Dockerfile.multiarch
I missed this when converting to `Dockerfile.multiarch`
Maybe this will help with #178 ?
> fix: copy the overlay folder into place
